### ISSUE TITLE
Problems with functions without declarations

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [WhenGryphonsFly/decomp-permuter#4]
```
/mnt/c/Users/H A M/Metroid/mf# python3 ../decomp-permuter-agbcc/permuter.py nonmatchings/CoreXShell
Loading...
nonmatchings/CoreXShell/base.c (CoreXShell)
No perm macros found. Defaulting to randomization.
Will try 1 different base sources.

[CoreXShell] base score = 0
iteration 1, 0 errors, score = 410
[CoreXShell] internal permuter failure.
Traceback (most recent call last):
  File "/mnt/c/Users/H A M/Metroid/decomp-permuter-agbcc/src/permuter.py", line 269, in try_eval_candidate
    return self._eval_candidate(seed)
  File "/mnt/c/Users/H A M/Metroid/decomp-permuter-agbcc/src/permuter.py", line 197, in _eval_candidate
    self._cur_cand.randomize_ast()
  File "/mnt/c/Users/H A M/Metroid/decomp-permuter-agbcc/src/candidate.py", line 81, in randomize_ast
    self.randomizer.randomize(self.ast, self.fn_name)
  File "/mnt/c/Users/H A M/Metroid/decomp-permuter-agbcc/src/randomizer.py", line 2456, in randomize
    method(fn, ast, indices, region, self.random)
  File "/mnt/c/Users/H A M/Metroid/decomp-permuter-agbcc/src/randomizer.py", line 2346, in perm_inline
    if match_cut(cand2, cut_expr, cut_types, [], typemap):
  File "/mnt/c/Users/H A M/Metroid/decomp-permuter-agbcc/src/randomizer.py", line 2307, in match_cut
    return ast_util.equal_ast(node, cut_node, cmp)
  File "/mnt/c/Users/H A M/Metroid/decomp-permuter-agbcc/src/ast_util.py", line 205, in equal_ast
    return equal(a, b)
  File "/mnt/c/Users/H A M/Metroid/decomp-permuter-agbcc/src/ast_util.py", line 201, in equal
    if not equal(getattr(a, name), getattr(b, name)):
  File "/mnt/c/Users/H A M/Metroid/decomp-permuter-agbcc/src/ast_util.py", line 181, in equal
    res = cmp(a, b)
  File "/mnt/c/Users/H A M/Metroid/decomp-permuter-agbcc/src/randomizer.py", line 2301, in cmp
    tp = decayed_expr_type(expr, typemap)
  File "/mnt/c/Users/H A M/Metroid/decomp-permuter-agbcc/src/ast_types.py", line 196, in decayed_expr_type
    return pointer_decay(expr_type(expr, typemap), typemap)
  File "/mnt/c/Users/H A M/Metroid/decomp-permuter-agbcc/src/ast_types.py", line 179, in expr_type
    fptr_type = resolve_typedefs(rec(expr), typemap)
  File "/mnt/c/Users/H A M/Metroid/decomp-permuter-agbcc/src/ast_types.py", line 104, in rec
    return expr_type(sub_expr, typemap)
  File "/mnt/c/Users/H A M/Metroid/decomp-permuter-agbcc/src/ast_types.py", line 127, in expr_type
    return typemap.var_types[node.name]
KeyError: 'CountPrimarySprite'

To reproduce the failure, rerun with: --seed 7743607712773704045
```

**Comment by H-A-M-G-E-R** [comment]
[CoreXShell.zip](https://github.com/user-attachments/files/17562201/CoreXShell.zip)
And here's what I'm permuting

**Comment by H-A-M-G-E-R** [comment]
now i realmatched it without permuter
https://decomp.me/scratch/2ioU9

**Comment by WhenGryphonsFly** [comment]
I don't know why I didn't get an email about this, but regardless this is the wrong venue. decomp-permuter-agbcc's scope is changing the *import script* to be easier for agbcc compared to upstream. Any changes to the *permuter itself* are outside of this repository's scope, and should be handled by upstream.
